In [11]:
import time
def monster(xx):
    
    from bs4 import BeautifulSoup
    soup=BeautifulSoup(xx,'html.parser')
    
    title=[]
    for i in soup.find_all("div",class_="job-tittle"):
        title.append(i.find_all("a",target="_blank")[0].text)
        
    company=[]
    for i in soup.find_all("span",class_="company-name"):
        company.append(i.text)
        
    yearofexp=[]
    for i in soup.find_all("div",class_="exp col-xxs-12 col-sm-3 text-ellipsis"):
        yearofexp.append(i.text.strip())
        
    salary=[]
    for i in soup.find_all("div",class_="package col-xxs-12 col-sm-4 text-ellipsis"):
        salary.append(i.text.strip())
        
    import pandas as pd
    table=pd.DataFrame({'Title':title,'Company':company,'Year Of Experience':yearofexp,
             'Salary':salary})
    return table


from selenium import webdriver
import os
path_tounzipfileie="C:/Users/Administrator/Desktop/Python/Data Scraping/geckodriver-v0.25.0-win64"
os.chdir(path_tounzipfileie)
browser=webdriver.Firefox(path_tounzipfileie)   
from bs4 import BeautifulSoup   
browser.get(url)
html=browser.page_source
master={}
master[0]=monster(html)
btns=browser.find_elements_by_class_name("btn-next-prev")
btns[0].click()
for i in range(1,4):
    btns=browser.find_elements_by_class_name("btn-next-prev")
    html=browser.page_source
    master[i]=monster(html)
    for btn in btns:
        if btn.text=="Next":
            btn.click()
            time.sleep(2)
import pandas as pd
master_table=pd.concat([master[i] for i in master],axis=0)
master_table

,Title,Company,Year Of Experience,Salary
0,Java Architect,Cognizant Technology Solutions India Pvt Ltd,10-16 Years,Not Specified
1,Data Science Consultant,IEverware Technologies Private Limited,4-8 Years,Not Specified
2,Data Science Developer,IEverware Technologies Private Limited,7-15 Years,Not Specified
3,Data Scientist - with a promising US based Pro...,Seventh Contact Hiring Solutions,5-10 Years,Not Specified
4,Data Science Consultant,IEverware Technologies Private Limited,4-8 Years,Not Specified
5,Data Science Developer,IEverware Technologies Private Limited,7-15 Years,Not Specified
6,LTI Hiring Data Science Professional F2F on 21...,Larsen & Toubro Infotech Ltd.,6-8 Years,Not Specified
7,Mega Recruitment Drive in Bangalore -Part Time...,Prayan Learning Private Limited,2-5 Years,Not Specified
8,Data Scientist-Artificial Intelligence- AI,IEverware Technologies Private Limited,4-12 Years,Not Specified
9,LTI Hiring Data Science Professional F2F on 10...,Larsen & Toubro Infotech Ltd.,3-10 Years,Not Specified
10,Artificial Intelligence / Data Scientist,Clean Harbors India LLP,5-10 Years,1000000-1400000 INR
11,"Trainer for Python, R programming, data scienc...",Speakwell Skills Academy Private Limited,1-2 Years,50000-90000 INR
12,"Database Architect(MySQL MongoDB, NodeJS or Py...",Elixa Tec,5-10 Years,Not Specified
13,Assistant Professor,MNR Solutions Private Limited,0-5 Years,Not Specified
14,Solution Architect Big Data,Wipro Limited,5-8 Years,Not Specified
15,LTI Hiring for Data Science - F2F on 20th July...,Larsen & Toubro Infotech Ltd.,4-10 Years,Not Specified
16,Data Architect,Narnia Soft,8-10 Years,Not Specified
17,Software Solution Developer,Aptusai Engineering Private Limited,1-4 Years,600000-900000 INR
18,Data Science & Machine Learning Architect,Druva Data Solutions Private Limited,12-14 Years,Not Specified
19,DATABASE SOLUTION ARCHITECT,Machintel Systems Private Limited,3-6 Years,300000-700000 INR
20,"Full-Stack Developer(NodeJs,Java android nativ...",Dixitech Hr Global Solutions Private Limited,3-6 Years,Not Specified
21,Data Scientist,Techno Facts solutions private limited,5-10 Years,100000-2000000 INR
22,Data Scientist at a Managerial level,V Employment Solutions,5-8 Years,Not Specified
23,Data Science Consultant Ghansoli Navi Mumbai,Asm Enterprise Solutions Private Limited,5-12 Years,Not Specified
24,Data Scientist,Solugenix India Private Limited,4-8 Years,Not Specified
25,Req: AI Data Scientist for a leading IT Compan...,Hr Dawn,7-17 Years,Not Specified
0,Java Architect,Cognizant Technology Solutions India Pvt Ltd,10-16 Years,Not Specified
1,Data Science Consultant,IEverware Technologies Private Limited,4-8 Years,Not Specified
2,Data Science Developer,IEverware Technologies Private Limited,7-15 Years,Not Specified
3,Data Scientist - with a promising US based Pro...,Seventh Contact Hiring Solutions,5-10 Years,Not Specified
...,...,...,...,...
20,Data Scientist,TECHNOSOFT GLOBAL SERVICES (P) LTD.,5-8 Years,Not Specified
21,Hiring | NLP Engineer | For a Product based Co...,IT Business Management Solutions India Private...,6-8 Years,Not Specified
22,Senior Data Engineer,Tech Mahindra Limited,3-5 Years,Not Specified
23,INTERVIEW DRIVE FOR SALES PROCESS IN REPUTED M...,Quess Corp Limited,1-4 Years,260000-270000 INR
24,Data Scientist,TECHNOSOFT GLOBAL SERVICES (P) LTD.,8-12 Years,Not Specified
0,Python Developer,Bloombrainz Consulting Services),2-6 Years,Not Specified
1,Big Data Developer - Banking and Capital Marke...,M2K Semantic Solutions Private Limited,3-5 Years,Not Specified
2,Business Intelligence and Data Visualization D...,M2K Semantic Solutions Private Limited,3-5 Years,Not Specified
3,Data Scientist,Quess Corp Limited,7-10 Years,Not Specified
4,Data Science TM/SDM,Golden Opportunities Private Limited,5-8 Years,Not Specified
5,Data Scientist Lead,Addon Manpower Solutions LLP,5-10 Years,Not Specified
6,Content Compliance Analyst Financial Products ...,CareerXperts Consulting,2-7 Years,Not Specified
7,EFRM Data Scientist,FIS Global Business Solutions India Private Li...,10-13 Years,Not Specified
8,Video Analytics Data Scientists for MNC in Ban...,Company Name Confidential,2-10 Years,Not Specified
9,AI Consultant - Artificial Intelligence,IEverware Technologies Private Limited,4-6 Years,Not Specified
10,Sr. Android Developer,MNR Solutions Private Limited,4-8 Years,1000000-2000000 INR
11,URGENT OPENING FOR CASHIER PROMOTER SALES COU...,First India Hr Solution,0-3 Years,110000-220000 INR
12,Data Scientist/Computer Vision Expert Required...,Junaati Technologies Private Limited,8-12 Years,Not Specified
13,Data Science,Jobs Expert Private Limited,4-6 Years,430000-760000 INR
14,Data Science,Jobs Expert Private Limited,3-5 Years,330000-540000 INR
15,Data Science,Jobs Expert Private Limited,3-5 Years,320000-560000 INR
16,Big Data Solution Architect,Tech Mahindra Limited,5-10 Years,0-3000000 INR
17,Technical Marketing Associate,Informatica business solutions pvt ltd,,Not Specified
18,Principal Machine Learning Engineer,CareerXperts Consulting,,Not Specified
19,Data Analyst,Ameriprise India Private limited,1-1 Years,Not Specified
20,phytoon developer,Ultramax Infotech Technologies Private Limited,0-2 Years,Not Specified
21,BI Data warehouse ETL Expert,Infonyx India Private Limited,1-3 Years,Not Specified
22,Data Scientist/Computer Vision Expert,Tech Mahindra Limited,8-12 Years,Not Specified
23,Java Architect,Cognizant Technology Solutions India Pvt Ltd,10-16 Years,Not Specified
24,Data Science Team Lead,Golden Opportunities Private Limited,3-5 Years,Not Specified

In [9]:
url='https://www.monsterindia.com/search/results?query=data%20science&searchId=c002b49e-c3e1-452a-8619-357a457ba23d'

In [8]:
master[3]

,Title,Company,Year Of Experience,Salary
0,Data Science,Taggd,7-12 Years,Not Specified
1,Lead Data Scientist- Only PHD Required,Jobs Expert Private Limited,10-20 Years,2000000-4500000 INR
2,Lead Data Scientist- Only PHD Required,Jobs Expert Private Limited,10-20 Years,2000000-4500000 INR
3,Senior Data Scientist,Company Name Confidential,8-15 Years,1000000-2000000 INR
4,Sr. Java Python Developer (10 yrs exp),ExterNetworks Inc,8-12 Years,Not Specified
5,Vice president of engineering,Multi Recruit,8-12 Years,Not Specified
6,Hadoop Admin,Winx Consulting Services,8-15 Years,Not Specified
7,Hadoop Admin,Winx Consulting Services,8-15 Years,790000-2020000 INR
8,Senior Developer,Flexi Careers India Private Limited,5-8 Years,Not Specified
9,Senior Full Stack Analytical Lead -Chennai/Ban...,Saggezza India Private Limited,4-10 Years,Not Specified
10,Sr. Full Stack Analytical Lead Role [HIDDEN TEXT],Best infosystems Ltd,6-10 Years,790000-1450000 INR
11,LTI Hiring Data Science Professional F2F on 11...,Larsen & Toubro Infotech Ltd.,4-9 Years,Not Specified
12,AI Developer,TECHNOSOFT GLOBAL SERVICES (P) LTD.,4-8 Years,Not Specified
13,Data Scientist,TECHNOSOFT GLOBAL SERVICES (P) LTD.,6-14 Years,Not Specified
14,Data Science,TECHNOSOFT GLOBAL SERVICES (P) LTD.,0-2 Years,Not Specified
15,Data Science & Machine learning,TECHNOSOFT GLOBAL SERVICES (P) LTD.,6-10 Years,Not Specified
16,Data Science,TECHNOSOFT GLOBAL SERVICES (P) LTD.,8-12 Years,Not Specified
17,Data Scientist,TECHNOSOFT GLOBAL SERVICES (P) LTD.,10-12 Years,Not Specified
18,Data Scientist,TECHNOSOFT GLOBAL SERVICES (P) LTD.,10-15 Years,Not Specified
19,Data Science,TECHNOSOFT GLOBAL SERVICES (P) LTD.,5-10 Years,Not Specified
20,Data Scientist,TECHNOSOFT GLOBAL SERVICES (P) LTD.,5-8 Years,Not Specified
21,Hiring | NLP Engineer | For a Product based Co...,IT Business Management Solutions India Private...,6-8 Years,Not Specified
22,Senior Data Engineer,Tech Mahindra Limited,3-5 Years,Not Specified
23,INTERVIEW DRIVE FOR SALES PROCESS IN REPUTED M...,Quess Corp Limited,1-4 Years,260000-270000 INR
24,Data Scientist,TECHNOSOFT GLOBAL SERVICES (P) LTD.,8-12 Years,Not Specified